export const cardPosts = [
  {
    id: 1,
    nomeUser: 'Lucas',
    imagem: 'https://picsum.photos/200/300?random=1',
    likes: 120,
    caption: 'Adoro este lugar! #natureza',
  },
  {
    id: 2,
    nomeUser: 'Maria',
    imagem: 'https://picsum.photos/200/300?random=2',
    likes: 75,
    caption: 'Amo animais! 🐶 #pets',
  },
  {
    id: 3,
    nomeUser: 'João',
    imagem: 'https://picsum.photos/200/300?random=3',
    likes: 45,
    caption: 'Vista incrível do topo da montanha. #aventura',
  },
  {
    id: 4,
    nomeUser: 'Ana',
    imagem: 'https://picsum.photos/200/300?random=4',
    likes: 98,
    caption: 'Dia perfeito na cidade. #urbano',
  },
  {
    id: 5,
    nomeUser: 'Pedro',
    imagem: 'https://picsum.photos/200/300?random=5',
    likes: 85,
    caption: 'Meu carro novo! 🚗 #carros',
  },
  {
    id: 6,
    nomeUser: 'Sofia',
    imagem: 'https://picsum.photos/200/300?random=6',
    likes: 110,
    caption: 'Praia e sol, o que mais eu preciso? #praia',
  },
  {
    id: 7,
    nomeUser: 'Carlos',
    imagem: 'https://picsum.photos/200/300?random=7',
    likes: 65,
    caption: 'Amo a tranquilidade das montanhas. #tranquilidade',
  },
  {
    id: 8,
    nomeUser: 'Julia',
    imagem: 'https://picsum.photos/200/300?random=8',
    likes: 150,
    caption: 'Brindando com amigos! 🍻 #celebracao',
  },
  {
    id: 9,
    nomeUser: 'Fernanda',
    imagem: 'https://picsum.photos/200/300?random=9',
    likes: 95,
    caption: 'Casa dos sonhos. #design',
  },
  {
    id: 10,
    nomeUser: 'Diego',
    imagem: 'https://picsum.photos/200/300?random=10',
    likes: 130,
    caption: 'Explorando novas rotas. #bicicleta',
  },
  {
    id: 11,
    nomeUser: 'Mariana',
    imagem: 'https://picsum.photos/200/300?random=11',
    likes: 80,
    caption: 'Flores lindas no jardim. #flores',
  },
  {
    id: 12,
    nomeUser: 'Ricardo',
    imagem: 'https://picsum.photos/200/300?random=12',
    likes: 60,
    caption: 'Apreciando o pôr do sol. #por-do-sol',
  },
];
